image: node:9

cache:
    paths:
        - node_modules/

before_script:
    - npm install

stages:
    - test
    - build

test:
    stage: test
    script: npm run test
build:
    stage: build
    script: npm run build
